#!/usr/bin/env python3
"""Export fresh browser cookies into per-platform Netscape files.

Runs on the HOST (where the browser and the OS keyring live) — a docker container
has neither, so cookie refresh happens here and the worker only reads the mounted
files (cookies/ -> /app/cookies).

    cookies/youtube.txt     youtube.com cookies
    cookies/instagram.txt   instagram.com cookies

Freshness is decided by file mtime: a file younger than --max-age-hours is skipped,
otherwise it is re-read from the browser. Safe to run on a schedule.

Examples:
    python scripts/refresh_cookies.py
    python scripts/refresh_cookies.py --force
    python scripts/refresh_cookies.py --browser firefox
    python scripts/refresh_cookies.py --max-age-hours 6
"""

import argparse
import os
import sys
import time

try:
    import browser_cookie3
except ModuleNotFoundError:
    sys.exit("browser_cookie3 is not installed: pip install browser_cookie3")

# domain -> (cookie file, login cookies required to consider the session real)
TARGETS = {
    "youtube.com": ("cookies/youtube.txt", {"LOGIN_INFO", "__Secure-3PSID", "SID"}),
    "instagram.com": ("cookies/instagram.txt", {"sessionid", "ds_user_id"}),
}

BROWSERS = {
    "chrome": browser_cookie3.chrome,
    "chromium": browser_cookie3.chromium,
    "brave": browser_cookie3.brave,
    "edge": browser_cookie3.edge,
    "firefox": browser_cookie3.firefox,
}


def _netscape_lines(cookiejar) -> list[str]:
    """Serialize a CookieJar into Netscape-format lines (as yt-dlp expects)."""
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by scripts/refresh_cookies.py — do not edit by hand.",
        "",
    ]
    for c in cookiejar:
        include_sub = "TRUE" if c.domain.startswith(".") else "FALSE"
        secure = "TRUE" if c.secure else "FALSE"
        expires = str(int(c.expires)) if c.expires else "0"
        lines.append("\t".join([c.domain, include_sub, c.path, secure, expires, c.name, c.value or ""]))
    return lines


def _is_fresh(path: str, max_age_hours: float) -> bool:
    if not os.path.exists(path):
        return False
    return (time.time() - os.path.getmtime(path)) < max_age_hours * 3600


def refresh(browser: str, force: bool, max_age_hours: float) -> int:
    loader = BROWSERS.get(browser)
    if loader is None:
        sys.exit(f"Unknown browser: {browser}. Available: {', '.join(BROWSERS)}")

    rc = 0
    for domain, (path, required) in TARGETS.items():
        if not force and _is_fresh(path, max_age_hours):
            print(f"skip {domain}: {path} still fresh (< {max_age_hours}h)")
            continue
        try:
            cj = loader(domain_name=domain)
        except Exception as e:  # noqa: BLE001 — one platform must not break the other
            print(f"error {domain}: cannot read cookies from {browser}: {e}")
            rc = 1
            continue

        names = {c.name for c in cj}
        missing = required - names
        if missing:
            # Do not overwrite a working file with an incomplete export. Usual cause:
            # no keyring/session access (e.g. cron instead of systemd --user) or a
            # logged-out browser. Keeping the old file is better than an empty one.
            print(f"warn {domain}: missing login cookies {sorted(missing)} — {path} left untouched. "
                  f"Log in to {browser} on {domain} (and check keyring access).")
            rc = 1
            continue

        os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write("\n".join(_netscape_lines(cj)) + "\n")
        print(f"ok {domain}: wrote {path} ({len(names)} cookies)")
    return rc


def main(argv=None) -> int:
    p = argparse.ArgumentParser(description="Refresh browser cookies for the devtrade worker")
    p.add_argument("--browser", default=os.getenv("COOKIES_FROM_BROWSER", "chrome"),
                   help="chrome/chromium/brave/edge/firefox (default chrome)")
    p.add_argument("--force", action="store_true", help="refresh even fresh files")
    p.add_argument("--max-age-hours", type=float,
                   default=float(os.getenv("COOKIES_MAX_AGE_HOURS", "6")),
                   help="freshness threshold in hours (default 6)")
    args = p.parse_args(argv)
    return refresh(args.browser, args.force, args.max_age_hours)


if __name__ == "__main__":
    sys.exit(main())
